# FluentOS Pacman 配置文件
# /etc/pacman.conf

[options]
# Arch 数据库路径
DBPath      = /var/lib/pacman/
CacheDir    = /var/cache/pacman/pkg/
LogFile     = /var/log/pacman.log
GPGDir      = /etc/pacman.d/gnupg/
HookDir     = /etc/pacman.d/hooks/

HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options
UseSyslog
Color
ILoveCandy
CheckSpace
VerbosePkgLists
DisableDownloadTimeout
ParallelDownloads = 5

# PGP 签名检查
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
#RemoteFileSigLevel = Required

# 核心仓库
[core]
Include = /etc/pacman.d/mirrorlist

# 额外仓库
[extra]
Include = /etc/pacman.d/mirrorlist

# 社区仓库
[community]
Include = /etc/pacman.d/mirrorlist

# 多重库
[multilib]
Include = /etc/pacman.d/mirrorlist

# FluentOS 自定义仓库
[fluentos]
SigLevel = Optional TrustAll
Server = https://github.com/sans65-ch/FluentOS/releases/download/repo/
